name: macOS

on:
  pull_request:
    branches: [ main ]

jobs:
  Test:
    uses: ./.github/workflows/execute-tests.yml
    with:
      os: "macos-13"
      workpath: "/Users/runner/work/doorstop/doorstop"
    secrets:
      CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
