name: Linux

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
    branches: [ main ]

jobs:
  Coverage:
    uses: ./.github/workflows/change-coverage.yml
    with:
      os: "ubuntu-latest"
      workpath: "/home/runner/work/doorstop/doorstop"
  Test:
    uses: ./.github/workflows/execute-tests.yml
    with:
      os: "ubuntu-latest"
      workpath: "/home/runner/work/doorstop/doorstop"
