name: Windows

on:
  pull_request:
    branches: [ main ]

jobs:
  Test:
    uses: ./.github/workflows/execute-tests.yml
    with:
      basepath: 'D:\'
      os: "windows-latest"
      workpath: 'C:\a\doorstop\doorstop'
