name: Linux

on:
  pull_request:
    branches: [ main ]

jobs:
  Coverage:
    uses: ./.github/workflows/change-coverage.yml
    with:
      os: "ubuntu-latest"
      workpath: "/home/runner/work/doorstop/doorstop"
    if: github.event_name == 'pull_request'

  Test:
    uses: ./.github/workflows/execute-tests.yml
    with:
      os: "ubuntu-latest"
      workpath: "/home/runner/work/doorstop/doorstop"
    secrets:
      CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
